name: Build

on:
  push:
    branches: ["*"]

jobs:
  win:
    runs-on: windows-2022
    name: Windows
    defaults:
      run:
        shell: msys2 {0}
    env:
      CCACHE_DIR: "${{github.workspace}}/.ccache"
      CCACHE_MAXSIZE: "1000M"
      CCACHE_COMPRESS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CCache Setup
        uses: actions/cache@v3
        with:
          path: |
            build/CMakeCache.txt

          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-build-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw32
          pacboy: >-
            gcc:p
            lld:p
            make:p
            ccache:p
            cmake:p

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_C_FLAGS="-fuse-ld=lld" -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..
          mingw32-make -j4

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: |
            Game/TonyRE.exe